{{- if .Values.mongoExpress.env.config.createConfigMap -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "svc-mongodb.mongoExpressEnvConfigmapName" . }}
  labels:
    {{- include "svc-mongodb.labels" . | nindent 4 }}
data:
  ME_CONFIG_BASICAUTH_ENABLED: "true"
  ME_CONFIG_BASICAUTH_USERNAME: {{ .Values.mongoExpress.username | quote }}
  {{- range $key, $value := .Values.mongoExpress.env.config.values }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
{{ end }}

{{- if .Values.mongoExpress.env.secret.createSecret -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "svc-mongodb.mongoExpressEnvSecretName" . }}
  labels:
    {{- include "svc-mongodb.labels" . | nindent 4 }}
type: Opaque
stringData:
  ME_CONFIG_BASICAUTH_PASSWORD: {{ .Values.mongoExpress.password | quote }}
  ME_CONFIG_MONGODB_URL: {{ include "svc-mongodb.mongoExpressConnString" . | quote }}
  {{- range $key, $value := .Values.mongoExpress.env.secret.values }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
{{ end }}
