apiVersion: v2
name: webapp
description: Fast-IT Meta Helm-Chart for WebApps
type: application
version: 0.1.0

dependencies:
  - name: webcomponent
    alias: back
    version: 0.1.0
    repository: file://../webcomponent
  - name: webcomponent
    alias: front
    version: 0.1.0
    repository: file://../webcomponent
    condition: front.enabled
  - name: svc-postgres
    alias: postgres
    version: 0.1.0
    repository: file://../svc-postgres
    condition: global.postgres.enabled
  - name: svc-mongodb
    alias: mongodb
    version: 0.1.0
    repository: file://../svc-mongodb
    condition: mongodb.enabled
