---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webcomponent.configmapName" .Subcharts.back }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
data:
  NAMESPACE: {{ .Release.Namespace | quote }}
  {{- if .Values.postgres.enabled }}
  POSTGRES_ADMIN_MAIL: {{ required "postgres.admin.email is required when postgres.enabled=true" .Values.postgres.admin.email | quote }}
  POSTGRES_ADMIN_PORT: {{ required "postgres.admin.port is required when postgres.enabled=true" .Values.postgres.admin.port | quote }}
  POSTGRES_ADMIN_URL: {{ include "svc-postgres.autoIngressHost" .Subcharts.postgres }}
  POSTGRES_USER: {{ required "postgres.database.owner is required when postgres.enabled=true" .Values.postgres.database.owner | quote }}
  POSTGRES_NAME: {{ required "postgres.database.name is required when postgres.enabled=true" .Values.postgres.database.name | quote }}
  POSTGRES_IP: "{{ include "svc-postgres.clusterName" .Subcharts.postgres }}-rw.{{ .Release.Namespace }}.svc.cluster.local"
  POSTGRES_PORT: {{ required "postgres.database.port is required when postgres.enabled=true" .Values.postgres.database.port | quote }}
  {{- end }}
  {{- if .Values.mongodb.enabled }}
  MONGO_ADMIN_PORT: '8081'
  MONGO_ADMIN_URL: {{ include "svc-mongodb.autoIngressHost" .Subcharts.mongodb }}
  MONGO_ADMIN_USER: {{ .Values.mongodb.mongoExpress.username | quote }}
  MONGO_IP: {{ printf "%s-svc" (include "svc-mongodb.clusterName" .Subcharts.mongodb) | quote }}
  MONGO_NAME: {{ include "svc-mongodb.clusterName" .Subcharts.mongodb | quote }}
  MONGO_PORT: '27017'
  MONGO_USER: {{ .Values.mongodb.cluster.database.user | quote }}
  {{- end }}
  {{- range $key, $value := .Values.back.env.config.values }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webcomponent.secretName" .Subcharts.back }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.postgres.enabled }}
  POSTGRES_ADMIN_PASS: {{ required "postgres.admin.password is required when postgres.enabled=true" .Values.postgres.admin.password | quote }}
  POSTGRES_PASS: {{ required "postgres.database.password is required when postgres.enabled=true" .Values.postgres.database.password | quote }}
  {{- end }}
  {{- if .Values.mongodb.enabled }}
  MONGO_ADMIN_PASS: {{ .Values.mongodb.mongoExpress.password | quote }}
  MONGO_PASS: {{ .Values.mongodb.cluster.database.password | quote }}
  {{- end }}
  {{- range $key, $value := .Values.back.env.secret.values }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
