{{- if .Values.front.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webcomponent.configmapName" .Subcharts.front }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
data:
  NAMESPACE: {{ .Release.Namespace | quote }}
  PROJECT_NAME: {{ .Release.Name | quote }}
  TITLE_PAGE: {{ .Release.Name | quote }}

  {{- with .Subcharts.back }}
    {{- $apiURL := include "webcomponent.autoIngressHost" . | trim }}
    {{- if $apiURL }}
  API_URL: {{ $apiURL | quote }}
    {{- end }}
  {{- end }}

  {{- range $key, $value := .Values.front.env.config.values }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webcomponent.secretName" .Subcharts.front }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.front.env.secret.values }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
{{- end -}}
