{{- if .Values.global.postgres.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "svc-postgres.configmapName" .Subcharts.postgres }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
data:
  PGADMIN_DEFAULT_EMAIL: {{ required "postgres.admin.email is required when env.config.createConfigMap=true" .Values.postgres.admin.email | quote }}
  {{- range $key, $value := .Values.postgres.env.config.values }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "svc-postgres.secretName" .Subcharts.postgres }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  PGADMIN_DEFAULT_PASSWORD: {{ required "postgres.admin.password is required when env.secret.createSecret=true" .Values.postgres.admin.password | quote }}
  {{- range $key, $value := .Values.postgres.env.secret.values }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
{{- end }}
